apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
      - name: manager
        command: ["/go/bin/dlv"]
        args: ["--listen=:2345", "--headless=true", "--api-version=2", "exec", "/go/src/github.com/kubeflow/kubeflow/components/profile-controller/manager"]
        env:
        - name: project
          valueFrom:
            configMapKeyRef:
              name: parameters
              key: project
        image: @@DOCKER_REGISTRY@@/gcr.io/kubeflow-images-public/profile-controller:e601b2226e534a4f8e0722cfc44ae4a919a90265c4c6c9e7a7a55fcb57032f25 
        ports:
        - containerPort: 2345
        securityContext:
          privileged: true
