apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistenceagent
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-persistenceagent
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: @@DOCKER_REGISTRY@@gcr.io/ml-pipeline/persistenceagent:0.1.31
        imagePullPolicy: IfNotPresent
      serviceAccountName: ml-pipeline-persistenceagent
